# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-17 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('Status', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Task_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('Status', models.CharField(choices=[('Not Started', 'Not Started'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed')], max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Created_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Due_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='User_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertask', to='wikisite.User'),
        ),
    ]
